  cache:
    key: "DEPENDENCIES"
    paths:
    - node_modules/


  Deploy review:
    image: lahautesociete/basic:1.3.0
    except:
     - preproduction
     - production
    environment:
      name: review/$CI_BUILD_REF_SLUG
      url: http://preprod.lahautesociete.com/path/to/$CI_BUILD_REF_SLUG/www/
      on_stop: stop_review
    script:
     - yarn
     - npm run build -- --assetsPublicPath="/path/to/$CI_BUILD_REF_SLUG/www/"
     - cd build
     - grunt ssh-deploy-release:review --branch="$CI_BUILD_REF_SLUG"


  stop_review:
    script:
     - yarn
     - cd build
     - grunt ssh-deploy-release:review --branch="$CI_BUILD_REF_SLUG" --remove
    when: manual
    except:
     - preproduction
     - production
    environment:
      name: review/$CI_BUILD_REF_SLUG
      action: stop
